'use client';
import { PropsWithChildren } from 'react';
import './globals.css';
import NavBar from './navbar';
import { Providers } from './providers';
import { Box, Flex } from '@chakra-ui/react';

export const metadata = {
  title: 'Footballsim',
  description: 'Generated by create next app',
};

function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Flex direction={'column'} p={'2'} gap={'2'}>
            <Box rounded={'md'} backgroundColor={'footballsim.700'}>
              <NavBar />
            </Box>
            <Box rounded={'md'} backgroundColor={'footballsim.700'} p={'2'}>
              {children}
            </Box>
          </Flex>
        </Providers>
      </body>
    </html>
  );
}

export default Layout;
